feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

server:
  servlet:
    contextPath: /v1

spring:
  mvc:
    throwExceptionIfNoHandlerFound: true